name: Terraform Docs

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install terraform-docs
        run: |
          curl -Lo /tmp/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
          tar -xzf /tmp/terraform-docs.tar.gz -C /tmp
          sudo mv /tmp/terraform-docs /usr/local/bin/terraform-docs

      - name: Generate Terraform docs
        run: terraform-docs .

      - name: Check for changes in README.md
        id: check-readme
        run: |
          if git diff --exit-code README.md; then
            echo "readme_updated=false" >> $GITHUB_OUTPUT
            echo "No changes to README.md file"
          else
            echo "readme_updated=true" >> $GITHUB_OUTPUT
            echo "Documentation has been updated in the README.md file"
          fi

      - name: Skip message (no changes to README.md)
        if: steps.check-readme.outputs.readme_updated == 'false'
        run: echo "Skipping rest of the steps because there are no changes to README.md."
        
      - name: Commit and push changes
        if: steps.check-readme.outputs.readme_updated == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: Auto-update Terraform documentation" || echo "No changes to commit"
          git push

      - name: Checkout alto-docs repository
        if: steps.check-readme.outputs.readme_updated == 'true'
        uses: actions/checkout@v3
        with:
          repository: Alto-Cloud-Technology/alto-docs # Replace with the actual org and repo name
          path: alto-docs
          token: ${{ secrets.PAT_TOKEN }}

      - name: Copy updated README.md to alto-docs
        if: steps.check-readme.outputs.readme_updated == 'true'
        run: |
          cp README.md alto-docs/infrastructure/terraform/$(basename "$GITHUB_REPOSITORY").md

      - name: Commit and push changes to alto-docs
        if: steps.check-readme.outputs.readme_updated == 'true'
        run: |
          cd alto-docs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add infrastructure/terraform/$(basename "$GITHUB_REPOSITORY").md
          git commit -m "docs: Update Terraform documentation for $GITHUB_REPOSITORY" || echo "No changes to commit"
          git push
